version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: plumtree
      POSTGRES_DB: fruitDB
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
